stages:
  - build

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
  tags: [shell_builder]
  stage: build
  script:
    -  docker build -t registry.gitlab.com/satt3l/slacker:latest --file build/Dockerfile .
    -  docker push registry.gitlab.com/satt3l/slacker:latest


shit:
  tags:
    - shell_builder
  script:
    - ls -l /dev
    - ls -l /zhipoa/xuj/
    - echo "I am fucking happy"
  only:
    - /fuck$/
