version: '3'
services:
  slacker:
    build:
      context: ${PROJECT_PATH}
    image: slacker-${BOT_NAME}:${BOT_VERSION}
    env_file:
     - ${LOCAL_PATH}/.env
    ports:
      - "3000:3000"
    networks:
      main:
        aliases:
          - ${BOT_NAME}.mabelly.com
networks:
  main:
